services:
  hazelcast1:
    image: hazelcast/hazelcast:5.3.1
    environment:
    - HZ_CLUSTERNAME=poc_cluster
    - HZ_NETWORK_PUBLICADDRESS=192.168.1.142:5701
    ports:
    - "5701:5701"
  hazelcast2:
    image: hazelcast/hazelcast:5.3.1
    environment:
    - HZ_CLUSTERNAME=poc_cluster
    - HZ_NETWORK_PUBLICADDRESS=192.168.1.142:5702
    ports:
    - "5702:5701"
  hazelcast3:
    image: hazelcast/hazelcast:5.3.1
    environment:
    - HZ_CLUSTERNAME=poc_cluster
    - HZ_NETWORK_PUBLICADDRESS=192.168.1.142:5703
    ports:
    - "5703:5701"
  management-center:
    image: hazelcast/management-center:5.3.1
    ports:
    - "18080:8080"
    environment:
    - MC_DEFAULT_CLUSTER=poc_cluster
    - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast1,hazelcast2