services:
  hazelcast:
    image: hazelcast/hazelcast:5.3.1
    ports:
    - "5701:5701"
  management-center:
    image: hazelcast/management-center:5.3.1
    ports:
    - "18080:8080"
    environment:
    - MC_DEFAULT_CLUSTER=dev
    - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast